name: Deploy
on:
  push:
    branches: [ main ]

  repository_dispatch:
    types: [trigger-alpine-container-build]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.QUAY_REPO }}/python
          tags: latest
          containerfiles: |
            ./Dockerfile
      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ vars.QUAY_REPO }}/python
          tags: latest
          registry: ${{ vars.QUAY_REGISTRY }}
          username: ${{ vars.QUAY_REGISTRY_USER }}
          password: ${{ secrets.QUAY_REGISTRY_PASSWORD }}





  # trigger https://github.com/net-sec/docker-alpine/actions/workflows/deploy.yaml
  trigger-alpine-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch alpine build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-alpine
          event-type: trigger-python-container-build

  # trigger https://github.com/net-sec/docker-dnssec/actions/workflows/deploy.yaml
  trigger-dnssec-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch dnssec build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-dnssec
          event-type: trigger-python-container-build

  # trigger https://github.com/net-sec/docker-keepalived/actions/workflows/deploy.yaml
  trigger-keepalived-build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Dispatch keepalived build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GLOBAL_GITHUB_ACCESS_TOKEN }}
          repository: net-sec/docker-keepalived
          event-type: trigger-python-container-build
